package com.lots.travel.store.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOTEL".
*/
public class HotelDao extends AbstractDao<Hotel, Long> {

    public static final String TABLENAME = "HOTEL";

    /**
     * Properties of entity Hotel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Img = new Property(1, String.class, "img", false, "IMG");
        public final static Property YwTotle = new Property(2, String.class, "ywTotle", false, "YW_TOTLE");
        public final static Property ViewSpotCountry = new Property(3, int.class, "viewSpotCountry", false, "VIEW_SPOT_COUNTRY");
        public final static Property Distance = new Property(4, String.class, "distance", false, "DISTANCE");
        public final static Property ScoreType = new Property(5, String.class, "scoreType", false, "SCORE_TYPE");
        public final static Property GpsGaode = new Property(6, String.class, "gpsGaode", false, "GPS_GAODE");
        public final static Property ScoreTotle = new Property(7, String.class, "scoreTotle", false, "SCORE_TOTLE");
        public final static Property Gps = new Property(8, String.class, "gps", false, "GPS");
        public final static Property Score = new Property(9, String.class, "score", false, "SCORE");
        public final static Property GpsBaidu = new Property(10, String.class, "gpsBaidu", false, "GPS_BAIDU");
        public final static Property ViewSpotCity = new Property(11, int.class, "viewSpotCity", false, "VIEW_SPOT_CITY");
        public final static Property GpsGoogle = new Property(12, String.class, "gpsGoogle", false, "GPS_GOOGLE");
        public final static Property CityName = new Property(13, String.class, "cityName", false, "CITY_NAME");
        public final static Property Zone = new Property(14, String.class, "zone", false, "ZONE");
        public final static Property AvgCostUnit = new Property(15, String.class, "avgCostUnit", false, "AVG_COST_UNIT");
        public final static Property CName = new Property(16, String.class, "cName", false, "C_NAME");
        public final static Property PercentPeople = new Property(17, String.class, "percentPeople", false, "PERCENT_PEOPLE");
        public final static Property Name = new Property(18, String.class, "name", false, "NAME");
        public final static Property Viewurl = new Property(19, String.class, "viewurl", false, "VIEWURL");
        public final static Property ShortDesc = new Property(20, String.class, "shortDesc", false, "SHORT_DESC");
        public final static Property Tag = new Property(21, String.class, "tag", false, "TAG");
        public final static Property AvgCost = new Property(22, String.class, "avgCost", false, "AVG_COST");
        public final static Property ScoreDesc = new Property(23, String.class, "scoreDesc", false, "SCORE_DESC");
        public final static Property ScheduleId = new Property(24, String.class, "scheduleId", false, "SCHEDULE_ID");
    }


    public HotelDao(DaoConfig config) {
        super(config);
    }
    
    public HotelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOTEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IMG\" TEXT," + // 1: img
                "\"YW_TOTLE\" TEXT," + // 2: ywTotle
                "\"VIEW_SPOT_COUNTRY\" INTEGER NOT NULL ," + // 3: viewSpotCountry
                "\"DISTANCE\" TEXT," + // 4: distance
                "\"SCORE_TYPE\" TEXT," + // 5: scoreType
                "\"GPS_GAODE\" TEXT," + // 6: gpsGaode
                "\"SCORE_TOTLE\" TEXT," + // 7: scoreTotle
                "\"GPS\" TEXT," + // 8: gps
                "\"SCORE\" TEXT," + // 9: score
                "\"GPS_BAIDU\" TEXT," + // 10: gpsBaidu
                "\"VIEW_SPOT_CITY\" INTEGER NOT NULL ," + // 11: viewSpotCity
                "\"GPS_GOOGLE\" TEXT," + // 12: gpsGoogle
                "\"CITY_NAME\" TEXT," + // 13: cityName
                "\"ZONE\" TEXT," + // 14: zone
                "\"AVG_COST_UNIT\" TEXT," + // 15: avgCostUnit
                "\"C_NAME\" TEXT," + // 16: cName
                "\"PERCENT_PEOPLE\" TEXT," + // 17: percentPeople
                "\"NAME\" TEXT," + // 18: name
                "\"VIEWURL\" TEXT," + // 19: viewurl
                "\"SHORT_DESC\" TEXT," + // 20: shortDesc
                "\"TAG\" TEXT," + // 21: tag
                "\"AVG_COST\" TEXT," + // 22: avgCost
                "\"SCORE_DESC\" TEXT," + // 23: scoreDesc
                "\"SCHEDULE_ID\" TEXT);"); // 24: scheduleId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOTEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Hotel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
 
        String ywTotle = entity.getYwTotle();
        if (ywTotle != null) {
            stmt.bindString(3, ywTotle);
        }
        stmt.bindLong(4, entity.getViewSpotCountry());
 
        String distance = entity.getDistance();
        if (distance != null) {
            stmt.bindString(5, distance);
        }
 
        String scoreType = entity.getScoreType();
        if (scoreType != null) {
            stmt.bindString(6, scoreType);
        }
 
        String gpsGaode = entity.getGpsGaode();
        if (gpsGaode != null) {
            stmt.bindString(7, gpsGaode);
        }
 
        String scoreTotle = entity.getScoreTotle();
        if (scoreTotle != null) {
            stmt.bindString(8, scoreTotle);
        }
 
        String gps = entity.getGps();
        if (gps != null) {
            stmt.bindString(9, gps);
        }
 
        String score = entity.getScore();
        if (score != null) {
            stmt.bindString(10, score);
        }
 
        String gpsBaidu = entity.getGpsBaidu();
        if (gpsBaidu != null) {
            stmt.bindString(11, gpsBaidu);
        }
        stmt.bindLong(12, entity.getViewSpotCity());
 
        String gpsGoogle = entity.getGpsGoogle();
        if (gpsGoogle != null) {
            stmt.bindString(13, gpsGoogle);
        }
 
        String cityName = entity.getCityName();
        if (cityName != null) {
            stmt.bindString(14, cityName);
        }
 
        String zone = entity.getZone();
        if (zone != null) {
            stmt.bindString(15, zone);
        }
 
        String avgCostUnit = entity.getAvgCostUnit();
        if (avgCostUnit != null) {
            stmt.bindString(16, avgCostUnit);
        }
 
        String cName = entity.getCName();
        if (cName != null) {
            stmt.bindString(17, cName);
        }
 
        String percentPeople = entity.getPercentPeople();
        if (percentPeople != null) {
            stmt.bindString(18, percentPeople);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(19, name);
        }
 
        String viewurl = entity.getViewurl();
        if (viewurl != null) {
            stmt.bindString(20, viewurl);
        }
 
        String shortDesc = entity.getShortDesc();
        if (shortDesc != null) {
            stmt.bindString(21, shortDesc);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(22, tag);
        }
 
        String avgCost = entity.getAvgCost();
        if (avgCost != null) {
            stmt.bindString(23, avgCost);
        }
 
        String scoreDesc = entity.getScoreDesc();
        if (scoreDesc != null) {
            stmt.bindString(24, scoreDesc);
        }
 
        String scheduleId = entity.getScheduleId();
        if (scheduleId != null) {
            stmt.bindString(25, scheduleId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Hotel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
 
        String ywTotle = entity.getYwTotle();
        if (ywTotle != null) {
            stmt.bindString(3, ywTotle);
        }
        stmt.bindLong(4, entity.getViewSpotCountry());
 
        String distance = entity.getDistance();
        if (distance != null) {
            stmt.bindString(5, distance);
        }
 
        String scoreType = entity.getScoreType();
        if (scoreType != null) {
            stmt.bindString(6, scoreType);
        }
 
        String gpsGaode = entity.getGpsGaode();
        if (gpsGaode != null) {
            stmt.bindString(7, gpsGaode);
        }
 
        String scoreTotle = entity.getScoreTotle();
        if (scoreTotle != null) {
            stmt.bindString(8, scoreTotle);
        }
 
        String gps = entity.getGps();
        if (gps != null) {
            stmt.bindString(9, gps);
        }
 
        String score = entity.getScore();
        if (score != null) {
            stmt.bindString(10, score);
        }
 
        String gpsBaidu = entity.getGpsBaidu();
        if (gpsBaidu != null) {
            stmt.bindString(11, gpsBaidu);
        }
        stmt.bindLong(12, entity.getViewSpotCity());
 
        String gpsGoogle = entity.getGpsGoogle();
        if (gpsGoogle != null) {
            stmt.bindString(13, gpsGoogle);
        }
 
        String cityName = entity.getCityName();
        if (cityName != null) {
            stmt.bindString(14, cityName);
        }
 
        String zone = entity.getZone();
        if (zone != null) {
            stmt.bindString(15, zone);
        }
 
        String avgCostUnit = entity.getAvgCostUnit();
        if (avgCostUnit != null) {
            stmt.bindString(16, avgCostUnit);
        }
 
        String cName = entity.getCName();
        if (cName != null) {
            stmt.bindString(17, cName);
        }
 
        String percentPeople = entity.getPercentPeople();
        if (percentPeople != null) {
            stmt.bindString(18, percentPeople);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(19, name);
        }
 
        String viewurl = entity.getViewurl();
        if (viewurl != null) {
            stmt.bindString(20, viewurl);
        }
 
        String shortDesc = entity.getShortDesc();
        if (shortDesc != null) {
            stmt.bindString(21, shortDesc);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(22, tag);
        }
 
        String avgCost = entity.getAvgCost();
        if (avgCost != null) {
            stmt.bindString(23, avgCost);
        }
 
        String scoreDesc = entity.getScoreDesc();
        if (scoreDesc != null) {
            stmt.bindString(24, scoreDesc);
        }
 
        String scheduleId = entity.getScheduleId();
        if (scheduleId != null) {
            stmt.bindString(25, scheduleId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Hotel readEntity(Cursor cursor, int offset) {
        Hotel entity = new Hotel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // img
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ywTotle
            cursor.getInt(offset + 3), // viewSpotCountry
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // distance
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // scoreType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // gpsGaode
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // scoreTotle
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // gps
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // score
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // gpsBaidu
            cursor.getInt(offset + 11), // viewSpotCity
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // gpsGoogle
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // cityName
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // zone
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // avgCostUnit
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // cName
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // percentPeople
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // name
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // viewurl
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // shortDesc
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // tag
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // avgCost
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // scoreDesc
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24) // scheduleId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Hotel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImg(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setYwTotle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setViewSpotCountry(cursor.getInt(offset + 3));
        entity.setDistance(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setScoreType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGpsGaode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setScoreTotle(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setGps(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setScore(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setGpsBaidu(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setViewSpotCity(cursor.getInt(offset + 11));
        entity.setGpsGoogle(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setCityName(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setZone(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setAvgCostUnit(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setCName(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPercentPeople(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setName(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setViewurl(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setShortDesc(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setTag(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setAvgCost(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setScoreDesc(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setScheduleId(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Hotel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Hotel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Hotel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
